### ISSUE TITLE
"Approximate" RTT

### ISSUE THREAD

**Issue by larseggert** [dthaler/dctcp#2]
Section 3.3 currently says:
```
   o  M is the fraction of sent bytes that encountered congestion during
      the previous observation window, where the observation window is
      chosen to be approximately the Round Trip Time (RTT).
```
What is meant by "approximately" here?

**Comment by larseggert** [comment]
Has this rewrite happened?

**Comment by sbens** [comment]
I did update this. Here's the latest text:

   o  M is the fraction of sent bytes that encountered congestion during
      the previous observation window, where the observation window is
      chosen to be approximately the Round Trip Time (RTT).  In
      particular, an observation window ends when all the sent bytes in
      flight at the beginning of the window have been acknowledged.

**Comment by larseggert** [comment]
Ah, I missed this - thanks
