### ISSUE TITLE
Mirja Kühlewind's review

### ISSUE THREAD

**Issue by larseggert** [dthaler/dctcp#6]
Mirja Kühlewind's review needs to be addressed: https://www.ietf.org/mail-archive/web/tcpm/current/msg09696.html

**Comment by pravb** [comment]
Yes we are aware of it and I will work on replying. Also working on the new draft. Sorry for the delay there has been some reorg recently so I couldn't devote time to this.

**Comment by larseggert** [comment]
No worries. I just add tickets here so we can keep track of what remains to be done.
